document.addEventListener("DOMContentLoaded", function () {
    const genreInput = document.getElementById('genreInput');
    const searchButton = document.getElementById('searchButton');

    genreInput.addEventListener('keydown', function (event) {
        if (event.key === "Enter") {
            searchGames();
        }
    });

    searchButton.addEventListener('click', function () {
        searchGames();
    });
});

function searchGames() {
    const genreInput = document.getElementById('genreInput').value.toLowerCase();

    if (!genreInput) {
        alert('Please enter a genre.');
        return;
    }

    const games = suggestGamesByGenre(genreInput);
    displayGames(games);
}

function suggestGamesByGenre(genre) {
    const gameSuggestions = {
        "action": [
            "A Way Out",
            "Alan Wake",
            "Alan Wake's American Nightmare",
            "Alien: Isolation",
            "Apex Legends",
            "Assassin's Creed",
            "Assassin's Creed II",
            "Assassin's Creed: Brotherhood",
            "Assassin's Creed: Revelations",
            "Assassin's Creed III",
            "Assassin's Creed IV: Black Flag",
            "Assassin's Creed Rogue",
            "Assassin's Creed Unity",
            "Assassin's Creed Syndicate",
            "Assassin's Creed Origins",
            "Assassin's Creed Odyssey",
            "Assassin's Creed Valhalla",
            "Battlefield 1",
            "Battlefield V",
            "Battlefield 4",
            "Battlefield 3",
            "Battlefield: Bad Company 2",
            "Battlefield 1942",
            "Battlefield 2142",
            "Battlefield Hardline",
            "BioShock",
            "BioShock 2",
            "BioShock Infinite",
            "Borderlands",
            "Borderlands 2",
            "Borderlands 3",
            "Call of Duty",
            "Call of Duty 2",
            "Call of Duty 4: Modern Warfare",
            "Call of Duty: Modern Warfare 2",
            "Call of Duty: Modern Warfare 3",
            "Call of Duty: Black Ops",
            "Call of Duty: Black Ops II",
            "Call of Duty: Black Ops III",
            "Call of Duty: Ghosts",
            "Call of Duty: Advanced Warfare",
            "Call of Duty: Infinite Warfare",
            "Call of Duty: World at War",
            "Call of Duty: WWII",
            "Crysis",
            "Crysis Warhead",
            "Crysis 2",
            "Crysis 3",
            "Dead Space",
            "Dead Space 2",
            "Dead Space 3",
            "Deus Ex",
            "Deus Ex: Human Revolution",
            "Deus Ex: Mankind Divided",
            "Destiny",
            "Destiny 2",
            "Doom (1993)",
            "Doom II",
            "Doom 3",
            "Doom (2016)",
            "Doom Eternal",
            "Far Cry",
            "Far Cry 2",
            "Far Cry 3",
            "Far Cry 4",
            "Far Cry 5",
            "Far Cry 6",
            "Gears of War",
            "Gears of War 2",
            "Gears of War 3",
            "Gears of War 4",
            "Gears 5",
            "Grand Theft Auto III",
            "Grand Theft Auto: Vice City",
            "Grand Theft Auto: San Andreas",
            "Grand Theft Auto IV",
            "Grand Theft Auto V",
            "Halo: Combat Evolved",
            "Halo 2",
            "Halo 3",
            "Halo 3: ODST",
            "Halo: Reach",
            "Halo 4",
            "Halo 5: Guardians",
            "Hitman",
            "Hitman 2",
            "Hitman 3",
            "Horizon Zero Dawn",
            "Just Cause",
            "Just Cause 2",
            "Just Cause 3",
            "Just Cause 4",
            "Left 4 Dead",
            "Left 4 Dead 2",
            "Max Payne",
            "Max Payne 2: The Fall of Max Payne",
            "Max Payne 3",
            "Metal Gear Solid",
            "Metal Gear Solid 2: Sons of Liberty",
            "Metal Gear Solid 3: Snake Eater",
            "Metal Gear Solid 4: Guns of the Patriots",
            "Metal Gear Solid V: Ground Zeroes",
            "Metal Gear Solid V: The Phantom Pain",
            "Metro 2033",
            "Metro: Last Light",
            "Metro Exodus",
            "Prey (2006)",
            "Prey (2017)",
            "Red Dead Redemption",
            "Red Dead Redemption 2",
            "Resident Evil",
            "Resident Evil 2 (Remake)",
            "Resident Evil 3 (Remake)",
            "Resident Evil 4",
            "Resident Evil 5",
            "Resident Evil 6",
            "Resident Evil 7: Biohazard",
            "Resident Evil Village",
            "Shadow of the Colossus (PS4)",
            "Star Wars Jedi: Fallen Order",
            "The Elder Scrolls V: Skyrim",
            "The Legend of Zelda: Breath of the Wild",
            "The Witcher: Enhanced Edition",
            "The Witcher 2: Assassins of Kings",
            "The Witcher 3: Wild Hunt - Game of the Year Edition",
            "Titanfall",
            "Titanfall 2",
            "Tom Clancy's Splinter Cell",
            "Tom Clancy's Splinter Cell: Pandora Tomorrow",
            "Tom Clancy's Splinter Cell: Chaos Theory",
            "Tom Clancy's Splinter Cell: Double Agent",
            "Tom Clancy's Splinter Cell: Conviction",
            "Tom Clancy's Splinter Cell: Blacklist",
            "Tom Clancy's Rainbow Six 3: Raven Shield",
            "Tom Clancy's Rainbow Six: Lockdown",
            "Tom Clancy's Rainbow Six: Vegas",
            "Tom Clancy's Rainbow Six: Vegas 2",
            "Tom Clancy's Rainbow Six: Siege",
            "Tom Clancy's Ghost Recon",
            "Tom Clancy's Ghost Recon 2",
            "Tom Clancy's Ghost Recon: Advanced Warfighter",
            "Tom Clancy's Ghost Recon: Advanced Warfighter 2",
            "Tom Clancy's Ghost Recon: Future Soldier",
            "Tom Clancy's Ghost Recon: Wildlands",
            "Tom Clancy's Ghost Recon: Breakpoint",
            "Tom Clancy's The Division",
            "Tom Clancy's The Division 2",
            "Uncharted: Drake's Fortune",
            "Uncharted 2: Among Thieves",
            "Uncharted 3: Drake's Deception",
            "Uncharted 4: A Thief's End",
            "Uncharted: The Lost Legacy",
            "Watch Dogs",
            "Watch Dogs 2",
            "Watch Dogs: Legion"
        ],
        
        "adventure": [
            "A Plague Tale: Innocence",
            "Alan Wake",
            "Alan Wake's American Nightmare",
            "Assassin's Creed IV: Black Flag",
            "Assassin's Creed Odyssey",
            "Assassin's Creed Origins",
            "Assassin's Creed Rogue",
            "Assassin's Creed Syndicate",
            "Assassin's Creed Unity",
            "Assassin's Creed Valhalla",
            "Bioshock Infinite",
            "Borderlands 3",
            "Control",
            "Control: Ultimate Edition",
            "Cyberpunk 2077",
            "Death Stranding",
            "Deathloop",
            "Deus Ex: Human Revolution",
            "Deus Ex: Mankind Divided",
            "Far Cry 6",
            "Ghost of Tsushima",
            "Ghostrunner",
            "Hitman 3",
            "Horizon Zero Dawn",
            "Kena: Bridge of Spirits",
            "Little Nightmares II",
            "Marvel's Spider-Man: Miles Morales",
            "Ori and the Will of the Wisps",
            "Psychonauts 2",
            "Ratchet & Clank: Rift Apart",
            "Red Dead Redemption 2",
            "Resident Evil Village",
            "Shadow of the Tomb Raider",
            "Star Wars Jedi: Fallen Order",
            "The Elder Scrolls V: Skyrim",
            "The Last of Us Part II",
            "The Legend of Zelda: Breath of the Wild",
            "The Medium",
            "The Outer Worlds",
            "The Witcher 3: Wild Hunt",
            "Uncharted 4: A Thief's End",
            "Watch Dogs 2",
            "A Way Out",
            "Assassin's Creed",
            "Assassin's Creed II",
            "Assassin's Creed: Brotherhood",
            "Assassin's Creed: Revelations",
            "Assassin's Creed III",
            "Assassin's Creed Syndicate",
            "BioShock",
            "BioShock 2",
            "BioShock Infinite",
            "Control",
            "Control: Ultimate Edition",
            "Cyberpunk 2077",
            "Far Cry 6",
            "Ghost of Tsushima",
            "Hitman 3",
            "Horizon Zero Dawn",
            "Just Cause",
            "Just Cause 2",
            "Just Cause 3",
            "Just Cause 4",
            "Kena: Bridge of Spirits",
            "Little Nightmares II",
            "Marvel's Spider-Man: Miles Morales",
            "Ori and the Will of the Wisps",
            "Psychonauts 2",
            "Ratchet & Clank: Rift Apart",
            "Red Dead Redemption 2",
            "Resident Evil Village",
            "Shadow of the Tomb Raider",
            "Star Wars Jedi: Fallen Order",
            "The Elder Scrolls V: Skyrim",
            "The Last of Us Part II",
            "The Legend of Zelda: Breath of the Wild",
            "The Medium",
            "The Outer Worlds",
            "The Witcher 3: Wild Hunt",
            "Uncharted 4: A Thief's End",
            "Watch Dogs 2"
        ],
        
        "rpg": [
            "Baldur's Gate 3",
            "Bloodborne",
            "Cyberpunk 2077",
            "Dark Souls III",
            "Dark Souls Remastered",
            "Demon's Souls",
            "Diablo III",
            "Disco Elysium",
            "Divinity Original Sin 2",
            "Dragon Age 2",
            "Dragon Age: Inquisition",
            "Dragon Age: Origins",
            "Elder Scrolls V: Skyrim",
            "Fallout 3",
            "Fallout 4",
            "Fallout: New Vegas",
            "Final Fantasy VII Remake",
            "Final Fantasy XIV: A Realm Reborn",
            "Kingdom Hearts",
            "Kingdom Hearts 2",
            "Kingdom Hearts 3",
            "Mass Effect",
            "Mass Effect 2",
            "Mass Effect 3",
            "Monster Hunter World",
            "Path of Exile",
            "Pillars of Eternity",
            "Persona 5",
            "Poe2",
            "Sekiro Shadows Die Twice",
            "Torchlight II",
            "The Elder Scrolls III: Morrowind",
            "The Elder Scrolls IV: Oblivion",
            "The Outer Worlds",
            "The Witcher",
            "The Witcher 2: Assassins of Kings",
            "The Witcher 3",
            "Wasteland 3",
            "World of Warcraft",
            "Cyberpunk 2077",
            "Dark Souls III",
            "Dark Souls Remastered",
            "Demon's Souls",
            "Diablo III",
            "Disco Elysium",
            "Divinity Original Sin 2",
            "Dragon Age 2",
            "Dragon Age: Inquisition",
            "Dragon Age: Origins",
            "Elder Scrolls V: Skyrim",
            "Fallout 3",
            "Fallout 4",
            "Fallout: New Vegas",
            "Final Fantasy VII Remake",
            "Final Fantasy XIV: A Realm Reborn",
            "Kingdom Hearts",
            "Kingdom Hearts 2",
            "Kingdom Hearts 3",
            "Mass Effect",
            "Mass Effect 2",
            "Mass Effect 3",
            "Monster Hunter World",
            "Path of Exile",
            "Pillars of Eternity",
            "Persona 5",
            "Poe2",
            "Sekiro Shadows Die Twice",
            "Torchlight II",
            "The Elder Scrolls III: Morrowind",
            "The Elder Scrolls IV: Oblivion",
            "The Outer Worlds",
            "The Witcher",
            "The Witcher 2: Assassins of Kings",
            "The Witcher 3",
            "Wasteland 3",
            "World of Warcraft"
        ],
        

        "fps": [
            "Apex Legends",
            "Battlefield 1",
            "Battlefield 3",
            "Battlefield 4",
            "Battlefield V",
            "Call of Duty 4: Modern Warfare",
            "Call of Duty: Black Ops",
            "Call of Duty: Black Ops Cold War",
            "Call of Duty: Black Ops II",
            "Call of Duty: Black Ops III",
            "Call of Duty: Ghosts",
            "Call of Duty: Infinite Warfare",
            "Call of Duty: Modern Warfare (2019)",
            "Call of Duty: Modern Warfare 2",
            "Call of Duty: Modern Warfare 3",
            "Call of Duty: Warzone",
            "Counter-Strike: Global Offensive",
            "Crysis",
            "Crysis 2",
            "Crysis 3",
            "Destiny 2",
            "Doom (2016)",
            "Doom Eternal",
            "Far Cry 3",
            "Far Cry 4",
            "Far Cry 5",
            "Far Cry 6",
            "Halo 3",
            "Halo 4",
            "Halo 5: Guardians",
            "Halo Infinite",
            "Left 4 Dead",
            "Left 4 Dead 2",
            "Overwatch",
            "Paladins",
            "Payday 2",
            "PlayerUnknown's Battlegrounds (PUBG)",
            "Rainbow Six Siege",
            "Titanfall",
            "Titanfall 2",
            "Valorant",
            "Warframe",
            "Wolfenstein: The New Order",
            "Wolfenstein: The Old Blood",
            "Wolfenstein II: The New Colossus",
            "Apex Legends",
            "Battlefield 1",
            "Battlefield 3",
            "Battlefield 4",
            "Battlefield V",
            "Call of Duty 4: Modern Warfare",
            "Call of Duty: Black Ops",
            "Call of Duty: Black Ops Cold War",
            "Call of Duty: Black Ops II",
            "Call of Duty: Black Ops III",
            "Call of Duty: Ghosts",
            "Call of Duty: Infinite Warfare",
            "Call of Duty: Modern Warfare (2019)",
            "Call of Duty: Modern Warfare 2",
            "Call of Duty: Modern Warfare 3",
            "Call of Duty: Warzone",
            "Counter-Strike: Global Offensive",
            "Crysis",
            "Crysis 2",
            "Crysis 3",
            "Destiny 2",
            "Doom (2016)",
            "Doom Eternal",
            "Far Cry 3",
            "Far Cry 4",
            "Far Cry 5",
            "Far Cry 6",
            "Halo 3",
            "Halo 4",
            "Halo 5: Guardians",
            "Halo Infinite",
            "Left 4 Dead",
            "Left 4 Dead 2",
            "Overwatch",
            "Paladins",
            "Payday 2",
            "PlayerUnknown's Battlegrounds (PUBG)",
            "Rainbow Six Siege",
            "Titanfall",
            "Titanfall 2",
            "Valorant",
            "Warframe",
            "Wolfenstein: The New Order",
            "Wolfenstein: The Old Blood",
            "Wolfenstein II: The New Colossus"
        ],
        

        "strategy": [
            "Age of Empires II: Definitive Edition",
            "Age of Empires III: Definitive Edition",
            "Age of Empires IV",
            "Age of Wonders: Planetfall",
            "Anno 1800",
            "Bannermen",
            "Battlefleet Gothic: Armada",
            "BattleTech",
            "Civilization VI",
            "Company of Heroes 2",
            "Crusader Kings III",
            "Desperados III",
            "Dota Underlords",
            "Endless Legend",
            "Endless Space 2",
            "Europa Universalis IV",
            "Frostpunk",
            "Gears Tactics",
            "Halo Wars 2",
            "Homeworld: Deserts of Kharak",
            "Into the Breach",
            "Iron Harvest",
            "Northgard",
            "Rise of Nations: Extended Edition",
            "Sid Meier's Civilization V",
            "Sid Meier's Civilization VI",
            "StarCraft II",
            "Stellaris",
            "Stronghold Crusader HD",
            "Surviving Mars",
            "Total War: Three Kingdoms",
            "Total War: Warhammer II",
            "Warcraft III: Reforged",
            "Warhammer 40,000: Gladius - Relics of War",
            "Warhammer 40,000: Mechanicus",
            "Wasteland 3",
            "XCOM 2",
            "Age of Empires II: Definitive Edition",
            "Age of Empires III: Definitive Edition",
            "Age of Empires IV",
            "Age of Wonders: Planetfall",
            "Anno 1800",
            "Bannermen",
            "Battlefleet Gothic: Armada",
            "BattleTech",
            "Civilization VI",
            "Company of Heroes 2",
            "Crusader Kings III",
            "Desperados III",
            "Dota Underlords",
            "Endless Legend",
            "Endless Space 2",
            "Europa Universalis IV",
            "Frostpunk",
            "Gears Tactics",
            "Halo Wars 2",
            "Homeworld: Deserts of Kharak",
            "Into the Breach",
            "Iron Harvest",
            "Northgard",
            "Rise of Nations: Extended Edition",
            "Sid Meier's Civilization V",
            "Sid Meier's Civilization VI",
            "StarCraft II",
            "Stellaris",
            "Stronghold Crusader HD",
            "Surviving Mars",
            "Total War: Three Kingdoms",
            "Total War: Warhammer II",
            "Warcraft III: Reforged",
            "Warhammer 40,000: Gladius - Relics of War",
            "Warhammer 40,000: Mechanicus",
            "Wasteland 3",
            "XCOM 2"
        ],
        

        "simulation": [
            "Airport CEO",
            "American Truck Simulator",
            "Anno 1800",
            "Astroneer",
            "Cities: Skylines",
            "Euro Truck Simulator 2",
            "Farming Simulator 19",
            "House Flipper",
            "Jurassic World Evolution",
            "Kerbal Space Program",
            "Microsoft Flight Simulator (2020)",
            "No Man's Sky",
            "Planet Coaster",
            "RollerCoaster Tycoon 2",
            "RollerCoaster Tycoon 3",
            "SimCity 4",
            "Spintires: MudRunner",
            "Stardew Valley",
            "Subnautica",
            "The Sims 4",
            "Train Sim World 2",
            "Two Point Hospital",
            "Airport CEO",
            "American Truck Simulator",
            "Anno 1800",
            "Astroneer",
            "Cities: Skylines",
            "Euro Truck Simulator 2",
            "Farming Simulator 19",
            "House Flipper",
            "Jurassic World Evolution",
            "Kerbal Space Program",
            "Microsoft Flight Simulator (2020)",
            "No Man's Sky",
            "Planet Coaster",
            "RollerCoaster Tycoon 2",
            "RollerCoaster Tycoon 3",
            "SimCity 4",
            "Spintires: MudRunner",
            "Stardew Valley",
            "Subnautica",
            "The Sims 4",
            "Train Sim World 2",
            "Two Point Hospital",
            "Airport CEO",
            "American Truck Simulator",
            "Anno 1800",
            "Astroneer",
            "Cities: Skylines",
            "Euro Truck Simulator 2",
            "Farming Simulator 19",
            "House Flipper",
            "Jurassic World Evolution",
            "Kerbal Space Program",
            "Microsoft Flight Simulator (2020)",
            "No Man's Sky",
            "Planet Coaster",
            "RollerCoaster Tycoon 2",
            "RollerCoaster Tycoon 3",
            "SimCity 4",
            "Spintires: MudRunner",
            "Stardew Valley",
            "Subnautica",
            "The Sims 4",
            "Train Sim World 2",
            "Two Point Hospital"
        ],
        
        "puzzle": [
            "Baba Is You",
            "Candy Crush Saga",
            "Celeste",
            "Cogs",
            "Crysis",
            "Crysis 2",
            "Crysis 3",
            "Crysis Warhead",
            "Crysis: Warhead",
            "Cut the Rope",
            "Deus Ex",
            "Deus Ex: Human Revolution",
            "Deus Ex: Mankind Divided",
            "Deus Ex: The Fall",
            "Hitman",
            "Hitman 2",
            "Hitman 3",
            "Hitman: Blood Money",
            "Hitman: Codename 47",
            "Hitman: Contracts",
            "Hitman: Silent Assassin",
            "Human: Fall Flat",
            "Inside",
            "Limbo",
            "Monument Valley",
            "Obduction",
            "Portal",
            "Portal 2",
            "Q.U.B.E. 2",
            "Scribblenauts Unlimited",
            "Scribblenauts Unmasked",
            "The Room",
            "The Talos Principle",
            "The Witness",
            "The Witness (2016)",
            "The Witness (2018)",
            "The Witness (2020)",
            "The Witness (2021)",
            "The Witness (2022)",
            "Thomas Was Alone",
            "Toki Tori",
            "Unravel",
            "Unravel 2",
            "World of Goo",
            "Zoombinis",
            "Baba Is You",
            "Candy Crush Saga",
            "Celeste",
            "Cogs",
            "Crysis",
            "Crysis 2",
            "Crysis 3",
            "Crysis Warhead",
            "Crysis: Warhead",
            "Cut the Rope",
            "Deus Ex",
            "Deus Ex: Human Revolution",
            "Deus Ex: Mankind Divided",
            "Deus Ex: The Fall",
            "Hitman",
            "Hitman 2",
            "Hitman 3",
            "Hitman: Blood Money",
            "Hitman: Codename 47",
            "Hitman: Contracts",
            "Hitman: Silent Assassin",
            "Human: Fall Flat",
            "Inside",
            "Limbo",
            "Monument Valley",
            "Obduction",
            "Portal",
            "Portal 2",
            "Q.U.B.E. 2",
            "Scribblenauts Unlimited",
            "Scribblenauts Unmasked",
            "The Room",
            "The Talos Principle",
            "The Witness",
            "The Witness (2016)",
            "The Witness (2018)",
            "The Witness (2020)",
            "The Witness (2021)",
            "The Witness (2022)",
            "Thomas Was Alone",
            "Toki Tori",
            "Unravel",
            "Unravel 2",
            "World of Goo",
            "Zoombinis"
        ],
        
        "sports": [
            "Madden NFL 06",
            "Madden NFL 07",
            "Madden NFL 08",
            "Madden NFL 09",
            "Madden NFL 10",
            "Madden NFL 11",
            "Madden NFL 12",
            "Madden NFL 13",
            "Madden NFL 15",
            "Madden NFL 16",
            "Madden NFL 17",
            "Madden NFL 18",
            "Madden NFL 19",
            "Madden NFL 20",
            "Madden NFL 21",
            "Madden NFL 22",
            "MLB 06: The Show",
            "MLB 07: The Show",
            "MLB 08: The Show",
            "MLB 09: The Show",
            "MLB 10: The Show",
            "MLB 11: The Show",
            "MLB 12: The Show",
            "MLB 13: The Show",
            "MLB The Show 14",
            "MLB The Show 15",
            "MLB The Show 16",
            "MLB The Show 17",
            "MLB The Show 18",
            "MLB The Show 19",
            "MLB The Show 20",
            "MLB The Show 21",
            "NBA 2K6",
            "NBA 2K7",
            "NBA 2K8",
            "NBA 2K9",
            "NBA 2K10",
            "NBA 2K11",
            "NBA 2K12",
            "NBA 2K13",
            "NBA 2K14",
            "NBA 2K15",
            "NBA 2K16",
            "NBA 2K17",
            "NBA 2K18",
            "NBA 2K19",
            "NBA 2K20",
            "NBA 2K21",
            "NBA 2K22",
            "NBA 2K23",
            "MLB 2006",
            "MLB 2007",
            "MLB 2008",
            "MLB 2009",
            "MLB 2010",
            "MLB 2011",
            "MLB 2012",
            "MLB 2013",
            "MLB 2014",
            "MLB 2015",
            "MLB 2016",
            "MLB 2017",
            "MLB 2018",
            "MLB 2019",
            "MLB 2020",
            "MLB 2021",
            "MLB 2022",
        ],
        "racing": [
            "Asphalt 9: Legends",
            "Assetto Corsa",
            "Burnout Paradise Remastered",
            "Crash Team Racing Nitro-Fueled",
            "Dirt 4",
            "Dirt Rally",
            "Dirt Rally 2.0",
            "F1 2019",
            "F1 2020",
            "F1 2021",
            "Forza Horizon 4",
            "Forza Horizon 5",
            "Forza Motorsport 7",
            "Grid",
            "Gran Turismo 7",
            "Hot Wheels Unleashed",
            "iRacing",
            "Mario Kart 8 Deluxe",
            "MotoGP 20",
            "Need for Speed Heat",
            "Need for Speed Hot Pursuit Remastered",
            "Need for Speed Payback",
            "Project CARS",
            "Project CARS 2",
            "Project CARS 3",
            "RIDE 4",
            "Rocket League",
            "Rush: A Disney Pixar Adventure",
            "The Crew 2",
            "Tony Hawk's Pro Skater 1 + 2",
            "WRC 9",
            "WRC 10",
            "Wreckfest",
            "Automobilista 2",
            "Monster Energy Supercross: The Official Videogame 4",
            "F1 2022",
            "Monster Jam Steel Titans 2",
            "Monster Truck Championship",
            "Monster Energy Supercross - The Official Videogame 5",
            "F1 2023",
            "MXGP 2020",
            "MXGP 2021",
            "MXGP 2022",
            "MXGP 2023",
            "Gravel",
            "Monster Truck Championship 2",
            "Street Power Soccer",
            "Monster Jam Steel Titans 3",
            "Monster Energy Supercross - The Official Videogame 6",
            "F1 2024",
            "MXGP 2024",
            "Monster Energy Supercross - The Official Videogame 7",
            "F1 2025",
            "MXGP 2025",
        ],
        
        "fighting": [
            "BlazBlue: Cross Tag Battle",
            "Dead or Alive 6",
            "Dragon Ball FighterZ",
            "Dragon Ball Xenoverse",
            "Dragon Ball Xenoverse 2",
            "FighterZ",
            "Guilty Gear Strive",
            "Guilty Gear Xrd -SIGN-",
            "Guilty Gear Xrd REV 2",
            "Injustice 2",
            "Jump Force",
            "Killer Instinct",
            "King of Fighters XIV",
            "Marvel vs. Capcom: Infinite",
            "Mortal Kombat 11",
            "Mortal Kombat XL",
            "Mortal Kombat X",
            "Skullgirls 2nd Encore",
            "Soulcalibur VI",
            "Street Fighter III: Third Strike",
            "Street Fighter IV",
            "Street Fighter V",
            "Street Fighter X Tekken",
            "Super Smash Bros. Brawl",
            "Super Smash Bros. for Wii U",
            "Super Smash Bros. Ultimate",
            "Tekken 7",
            "Ultimate Marvel vs. Capcom 3",
            "Virtua Fighter 5: Final Showdown",
            "Dead or Alive 5",
            "Injustice: Gods Among Us",
            "Tekken 6",
            "Soulcalibur V",
            "Mortal Kombat 9",
            "BlazBlue: Central Fiction",
            "Guilty Gear Xrd -REVELATOR-",
            "The King of Fighters XIII",
            "Persona 4 Arena Ultimax",
            "Ultimate Marvel vs. Capcom 3",
            "Skullgirls",
            "Divekick",
            "Street Fighter X Tekken",
            "Aquapazza: Aquaplus Dream Match",
            "Guilty Gear XX Accent Core Plus R",
            "Vanguard Princess",
            "Persona 4 Arena",
            "Dead or Alive 4",
            "BlazBlue: Chrono Phantasma Extend",
            "Koihime Enbu",
            "Nitroplus Blasterz: Heroines Infinite Duel",
            "JoJo's Bizarre Adventure: All-Star Battle",
            "Marvel vs. Capcom 2: New Age of Heroes",
            "Virtua Fighter 4: Evolution",
            "Tekken 5: Dark Resurrection",
            "Street Fighter Alpha 3",
            "Guilty Gear XX Accent Core",
            "Soulcalibur II",
            "Mortal Kombat II",
            "Super Street Fighter II Turbo",
            "Tekken 3",
            "Virtua Fighter 2",
            "Street Fighter II: Champion Edition",
            "Street Fighter",
            "Mortal Kombat",
            "Karate Champ",
            "Yie Ar Kung-Fu",
            "Punch-Out!!",
            "Street Fighter II",
            "Tekken Tag Tournament 2",
            "Marvel vs. Capcom 3: Fate of Two Worlds",
            "Guilty Gear Xrd -REVELATOR-",
            "BlazBlue: Continuum Shift Extend",
            "Super Street Fighter IV: Arcade Edition",
            "Virtua Fighter 5",
            "Dead or Alive 2",
            "Street Fighter III: 2nd Impact",
            "Mortal Kombat 4",
            "King of Fighters '98",
            "Soulcalibur",
            "Tekken 2",
            "Virtua Fighter",
            "Street Fighter II Turbo",
            "World Heroes",
            "Fatal Fury: King of Fighters",
            "Samurai Shodown",
            "Super Smash Bros. Melee",
            "Power Stone",
            "Tobal No. 1",
            "Bio F.R.E.A.K.S.",
            "Kakuto Chojin: Back Alley Brutal",
            "K-1 World Grand Prix",
            "Virtua Fighter Kids",
            "Martial Masters",
            "Super Dragon Ball Z",
            "Destrega",
            "Battle Arena Toshinden 2",
            "King of Fighters '94",
            "Vampire Savior",
            "Street Fighter: The Movie",
            "Mortal Kombat 3",
            "Art of Fighting",
            "Killer Instinct 2",
            "World Heroes Perfect",
            "Fatal Fury Special",
            "Samurai Shodown II",
            "Primal Rage",
            "Mace: The Dark Age",
            "Martial Champion",
            "Tao Feng: Fist of the Lotus",
            "Ehrgeiz",
            "Tatsunoko vs. Capcom: Ultimate All-Stars",
            "Shaq Fu",
            "Survival Arts",
            "Galactic Warriors",
            "Darkstalkers: The Night Warriors",
            "Ultra Vortek",
            "Mortal Kombat vs. DC Universe",
            "The Outfoxies",
            "Teenage Mutant Ninja Turtles: Tournament Fighters",
            "Battle Tycoon: Flash Hiders SFX",
            "Asura Buster: Eternal Warriors",
            "Kizuna Encounter",
            "Matrimelee",
            "Groove on Fight",
            "Sango Fighter",
            "Martial Masters",
            "Monster",
            "Fighter's History Dynamite",
            "War Gods",
            "Survival Arts",
            "Aggressors of Dark Kombat",
            "Cyberbots: Fullmetal Madness",
            "Tuff E Nuff",
            "Knuckle Heads",
            "Criticom",
            "Pit-Fighter",
            "Time Killers",
            "Blood Warrior",
            "Holosseum",
            "Dyna Gear",
            "3 Count Bout",
            "Hard Edge",
            "Oretachi Game Center: Samurai Shodown",
            "Joy Mech Fight",
            "Card Sagas Wars",
        ],
        
        "horror": [
            "Alien: Isolation",
            "Amnesia: A Machine for Pigs",
            "Amnesia: Rebirth",
            "Amnesia: The Dark Descent",
            "Bloodborne",
            "Call of Cthulhu: Dark Corners of the Earth",
            "Condemned: Criminal Origins",
            "Control",
            "Dead by Daylight",
            "Dead Space",
            "Dead Space 2",
            "Dead Space 3",
            "Devotion",
            "Doki Doki Literature Club!",
            "Fatal Frame",
            "Fatal Frame II: Crimson Butterfly",
            "Fatal Frame III: The Tormented",
            "Fatal Frame IV: Mask of the Lunar Eclipse",
            "F.E.A.R.",
            "F.E.A.R. 2: Project Origin",
            "F.E.A.R. 3",
            "Layers of Fear",
            "Manhunt",
            "Outlast",
            "Outlast 2",
            "Penumbra: Black Plague",
            "Penumbra: Overture",
            "Penumbra: Requiem",
            "Resident Evil",
            "Resident Evil 2 (Remake)",
            "Resident Evil 3 (Remake)",
            "Resident Evil 4",
            "Resident Evil 5",
            "Resident Evil 6",
            "Resident Evil 7: Biohazard",
            "S.T.A.L.K.E.R.: Shadow of Chernobyl",
            "S.T.A.L.K.E.R.: Clear Sky",
            "S.T.A.L.K.E.R.: Call of Pripyat",
            "Silent Hill",
            "Silent Hill 2",
            "Silent Hill 3",
            "Silent Hill 4: The Room",
            "Silent Hill: Homecoming",
            "Silent Hill: Origins",
            "Silent Hill: Shattered Memories",
            "Siren",
            "Siren: Blood Curse",
            "The Evil Within",
            "The Evil Within 2",
            "Until Dawn",
            "Visage"
        ],
        
        "survival": [
            "7 Days to Die",
            "Alien: Isolation",
            "ARK: Survival Evolved",
            "Conan Exiles",
            "Dark Souls",
            "Dark Souls II",
            "Dark Souls III",
            "DayZ",
            "Dead by Daylight",
            "Dead Island",
            "Dead Space",
            "Don't Starve",
            "Dying Light",
            "Frostpunk",
            "Green Hell",
            "H1Z1: King of the Kill",
            "Left 4 Dead",
            "Left 4 Dead 2",
            "Minecraft",
            "Miscreated",
            "No Man's Sky",
            "Osiris: New Dawn",
            "Outlast",
            "Outlast 2",
            "Project Zomboid",
            "Rust",
            "S.T.A.L.K.E.R.: Shadow of Chernobyl",
            "S.T.A.L.K.E.R.: Clear Sky",
            "S.T.A.L.K.E.R.: Call of Pripyat",
            "Scum",
            "Seven Days in Purgatory",
            "State of Decay",
            "State of Decay 2",
            "Stranded Deep",
            "Subnautica",
            "Subnautica: Below Zero",
            "Survive the Nights",
            "Terraria",
            "The Forest",
            "The Long Dark",
            "The Raft",
            "The Stranded Deep",
            "The Walking Dead: Saints & Sinners",
            "The Wild Eight",
            "This War of Mine",
            "Unturned",
            "Valheim",
            "We Happy Few",
            "Withstand: Survival",
            "World War Z",
            "Zombi",
            "Zombie Army 4: Dead War",
            "Zombie Night Terror",
            "Zombie Panic! Source",
            "Zombie Playground",
            "Zomboid"
        ]
        
        
        // Add more genres and game suggestions as needed
    };

    const lowercaseGenre = genre.toLowerCase();

    return gameSuggestions[lowercaseGenre] || [];
}

function displayGames(games) {
    const gameList = document.getElementById('gameList');
    gameList.innerHTML = '';

    if (games.length === 0) {
        gameList.innerHTML = '<p>No games found for this genre.</p>';
    } else {
        games.forEach(game => {
            const listItem = document.createElement('li');
            listItem.textContent = game;
            gameList.appendChild(listItem);
        });
    }
}
